### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by mxmilkiib** [jimm/keymaster#2]
On Arch Linux;

```
20:07:30 milk@red:~/src/keymaster main ± make
g++  -std=c++14 -MD -MP -g  -I/usr/lib/wx/include/gtk3-unicode-3.2 -I/usr/include/wx-3.2 -DWXUSINGDLL -D__WXGTK3__ -D__WXGTK__ -D_FILE_OFFSET_BITS=64   -c -o src/clock.o src/clock.cpp
In file included from src/clock.cpp:2:
src/clock.h: In member function ‘bool Clock::is_running()’:
src/clock.h:32:37: error: invalid operands of types ‘pthread_t’ {aka ‘long unsigned int’} and ‘std::nullptr_t’ to binary ‘operator!=’
   32 |   bool is_running() { return thread != nullptr; }
      |                              ~~~~~~~^~~~~~~~~~
src/clock.cpp: In constructor ‘Clock::Clock(std::vector<Input*>&)’:
src/clock.cpp:20:31: error: cannot convert ‘std::nullptr_t’ to ‘pthread_t’ {aka ‘long unsigned int’} in initialization
   20 |   : inputs(km_inputs), thread(nullptr)
      |                               ^~~~~~~
      |                               |
      |                               std::nullptr_t
src/clock.cpp: In member function ‘void Clock::stop()’:
src/clock.cpp:48:14: error: invalid operands of types ‘pthread_t’ {aka ‘long unsigned int’} and ‘std::nullptr_t’ to binary ‘operator==’
   48 |   if (thread == nullptr)
      |       ~~~~~~~^~~~~~~~~~
src/clock.cpp:50:12: error: cannot convert ‘std::nullptr_t’ to ‘pthread_t’ {aka ‘long unsigned int’} in assignment
   50 |   thread = nullptr;
      |            ^~~~~~~
make: *** [<builtin>: src/clock.o] Error 1
```

**Comment by jimm** [comment]
Thanks for letting me know about this. I'll see if I can reproduce this in a linux Docker instance or something like that; I don't have direct access to a linux machine.

In the meantime, can you replace all of the `nullptr` occurrences for `thread` in that file with `0` instead? That _might_ work.

BTW, I'm actually rewriting KeyMaster in JUCE (https://juce.com/) which will allow for a nicer cross-platform GUI and hopefully better cross-platform portability and realtime MIDI handling. See https://github.com/jimm/juce-keymaster though it's not done quite yet.

**Comment by jimm** [comment]
You might also have to change the one in `clock.h` on line 32 as well.

**Comment by jimm** [comment]
I'm having trouble getting an arch linux installation up and configured (I don't know pacman well and updating things didn't go very well, let alone trying to install anything). However, in an Ubuntu image I saw the same errors you saw but in `src/input.cpp` instead. Replacing the `nullptr` instances with `0` where the errors were fixed the errors.

**Comment by jimm** [comment]
I checked in those changes a few weeks ago. @mxmilkiib can you please confirm that this fixed the problem?

**Comment by mxmilkiib** [comment]
Doing some RL things, will seek to get back to this soon! Thanks for your help
